### PR TITLE
Adding the ability to resolve hostnames locally instead of passing them to server.

### PR DESCRIPTION
**Pull request by tarekwiz**
By setting a bool "ResolveHostnamesLocally" to true, hostnames are evaluated on the localmachine before they are passed to the remote socks5 server.

### CODE REVIEW

**Comment by GF-Huang** [comment]
1. You can resolve the hostnames before `Socklient.Connect(...)`, and pass the IPAddress to `Connect(IPAddress ...)` instead of `Connect(string ...)`. Resolving hostnames internally is not necessary.

2. `Dns.GetHostAddresses` will block current thread, you should use `Dns.GetHostAddressesAsync` instead if you're in async context.

```
var address = (await Dns.GetHostAddressesAsync(destHost))[0];
var socklient = new Socklient(...);
await socklient.ConnectAsync(address, ...);
```

**Comment by tarekwiz** [comment]
Yes you can resolve the hostnames before `Socklient.Connect(...)`, but it's easier to just have the functionality internally. I will fix the thread blocking call now and add it.

**Comment by GF-Huang** [comment]
It's not necessary to call `IPAddress.TryParse`, `Dns.GetHostAddresses` do this inside itself.

[Dns.GetHostAddresses Source Code](https://referencesource.microsoft.com/#System/net/System/Net/DNS.cs,eb768b1333d21612)

image

---------------------------------------

The same to `Dns.GetHostAddressesAsync`.

[Dns.GetHostAddressesAsync Source Code](https://referencesource.microsoft.com/#System/net/System/Net/DNS.cs,17f3136c71e92be2)

image

---------------------------------------

Another, you can assign to `destAddress` instead of `destHost`, not necessary to convert it to `string` because it is already an address.

image

**Comment by GF-Huang** [comment]
Add another point, do you have read RFC 1928 ?  I think this way to resolve the hostname locally, contrary to the original intention of [RFC 1928](https://tools.ietf.org/html/rfc1928)

image

**Comment by tarekwiz** [comment]
Should be fixed now.

**Pull request closed without merging**
